### ISSUE TITLE
404 on nginx proxy_pass

### ISSUE THREAD

**Issue by t3pfaffe** [ONLYOFFICE/document-server-proxy#12]
This is my config. 10.0.0.121:3080 is my document servers ip/port.
It returns a 404 when I navigate to the url that the server is listening on and even adds the /welcome/ subdomain. This makes no sense. I have disabled all unnecessary options and even re wrote some of the parts verbatim from the example given as to rule out any errors. Any ideas? It is  

This is the error given on the browser side:
`Error loading this URI: Protocol error (unknownError): Could not load the source for https://office.pfaffe.me/welcome/.
Error: Failed to fetch https://office.pfaffe.me/welcome/. Code 2153390067.
Stack: onResponse@resource://devtools/shared/DevToolsUtils.js:544:16
onStopRequest@resource://gre/modules/NetUtil.jsm:123:17
Line: 544, column: 16`

![image](https://user-images.githubusercontent.com/16065962/62129695-e367a500-b2c6-11e9-9d4b-586cdaac9d0c.png)

**Comment by jmt99** [comment]
have u  solve it?

**Comment by t3pfaffe** [comment]
No
