### ISSUE TITLE
Help for HAproxy virtual-path

### ISSUE THREAD

**Issue by pasechnik2307** [ONLYOFFICE/document-server-proxy#5]
I need the same config for HAproxy. I tried but my config do not work.

**My haproxy.conf:**

frontend cloud
    bind *:80
    mode http
    acl is_oo path_beg /oo   
    option forwardfor header X-Real-IP
    use_backend ooffice if is_oo
    default_backend cloudnodes

backend cloudnodes
    mode    http
    balance roundrobin
    option forwardfor
    http-request set-header X-Forwarded-Port %[dst_port]
    cookie SERVERID insert indirect nocache
    server  own-01 1.2.3.40:80 check cookie own-01 check inter 1000 rise 1 fall 1
    server  own-02 1.2.3.41:80 check cookie own-02 check inter 1000 rise 1 fall 1

backend ooffice
    mode    http
    option httpclose
    option forwardfor header X-Real-IP
    http-request set-header X-Forwarded-Port %[dst_port] 
    http-request add-header X-Forwarded-For %[src]
    http-request set-header X-Client-IP %[src]
    http-request set-header X-Forwarded-Proto http
    http-request set-header Forwarded proto=http
    http-request add-header Host %[src]
    http-request add-header X-Forwarded-Host %[src]
    http-request add-header X-Forwarded-Server %[src]
    reqrep ^([^\ :]*)\ /oo(.*)     \1\ \2
    server  oo-01 1.2.3.4:80

**Comment by agolybev** [comment]
Hi @pasechnik2307, I'm not familar with haproxy, but if you want use virtual path you should put it into `X-Forwarded-Host` header, like this:
`http-request add-header X-Forwarded-Host %[src]/documentserver-virtual-path`
But I'm not sure in syntax.

**Comment by agolybev** [comment]
Hi @pasechnik2307, Was my comment useful to you?

**Comment by pasechnik2307** [comment]
Hello @agolybev , yes, thank you, but it's still does not work(

**Comment by pasechnik2307** [comment]
@agolybev Thank you in advance)

**Comment by agolybev** [comment]
Hi @pasechnik2307, I've added haproxy sample config for proxying virtual path. See the example [here](https://github.com/ONLYOFFICE/document-server-proxy/blob/master/haproxy/proxy-to-virtual-path.cfg).
